// <auto-generated />
using System;
using AuropaqPedidos.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuropaqPedidos.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuropaqPedidosDbContext))]
    [Migration("20260910164601_AgregarConsolidacion")]
    partial class AgregarConsolidacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.AsignacionConsolidacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DetalleConsolidacionId")
                        .HasColumnType("int");

                    b.Property<int>("DetalleRequisicionOrigenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetalleConsolidacionId");

                    b.HasIndex("DetalleRequisicionOrigenId");

                    b.ToTable("AsignacionesConsolidacion", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Consolidacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.ToTable("Consolidaciones", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleConsolidacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ConsolidacionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsolidacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("DetallesConsolidacion", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleRequisicion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("CantidadSolicitada")
                        .HasColumnType("int");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductoId")
                        .HasColumnType("int");

                    b.Property<int>("RequisicionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("RequisicionId");

                    b.ToTable("DetallesRequisicion", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DistribucionRequisicion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("DetalleRequisicionId")
                        .HasColumnType("int");

                    b.Property<int>("SedeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DetalleRequisicionId");

                    b.HasIndex("SedeId");

                    b.ToTable("DistribucionesRequisicion", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Nit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.HistorialRequisicion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("RequisicionId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequisicionId");

                    b.ToTable("HistorialRequisicion", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Periodo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaFinSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaInicioSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Anio", "Mes")
                        .IsUnique();

                    b.ToTable("Periodos", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Producto", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UnidadMedidaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("UnidadMedidaId");

                    b.ToTable("Productos", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Requisicion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("PeriodoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioCreacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PeriodoId");

                    b.HasIndex("EmpresaId", "PeriodoId")
                        .IsUnique();

                    b.ToTable("Requisiciones", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Sede", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Ciudad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contacto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Sedes", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.SolicitudProductoCatalogo", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<string>("MotivoResolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreSolicitado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductoResultanteId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResolucionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("ProductoResultanteId");

                    b.ToTable("SolicitudesProductoCatalogo", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.UnidadMedida", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Infrastructure.Persistence.ContadorIdentificador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Valor")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContadorIdentificadores", (string)null);
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.AsignacionConsolidacion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.DetalleConsolidacion", null)
                        .WithMany("Asignaciones")
                        .HasForeignKey("DetalleConsolidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.DetalleRequisicion", "DetalleRequisicionOrigen")
                        .WithMany()
                        .HasForeignKey("DetalleRequisicionOrigenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetalleRequisicionOrigen");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Consolidacion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleConsolidacion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Consolidacion", null)
                        .WithMany("Detalles")
                        .HasForeignKey("ConsolidacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleRequisicion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.Requisicion", null)
                        .WithMany("Detalles")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DistribucionRequisicion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.DetalleRequisicion", null)
                        .WithMany("Distribuciones")
                        .HasForeignKey("DetalleRequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.Sede", "Sede")
                        .WithMany()
                        .HasForeignKey("SedeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sede");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.HistorialRequisicion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Requisicion", null)
                        .WithMany("Historial")
                        .HasForeignKey("RequisicionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Producto", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Categoria", "Categoria")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.UnidadMedida", "UnidadMedida")
                        .WithMany()
                        .HasForeignKey("UnidadMedidaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UnidadMedida");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Requisicion", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Sede", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.SolicitudProductoCatalogo", b =>
                {
                    b.HasOne("AuropaqPedidos.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuropaqPedidos.Domain.Entities.Producto", "ProductoResultante")
                        .WithMany()
                        .HasForeignKey("ProductoResultanteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");

                    b.Navigation("ProductoResultante");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Consolidacion", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleConsolidacion", b =>
                {
                    b.Navigation("Asignaciones");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.DetalleRequisicion", b =>
                {
                    b.Navigation("Distribuciones");
                });

            modelBuilder.Entity("AuropaqPedidos.Domain.Entities.Requisicion", b =>
                {
                    b.Navigation("Detalles");

                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
